# Use root/example as user/password credentials
version: '3.5'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9999
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.10:27017:27017"
    networks:
      - ftnet

networks:
  ftnet:
    driver: bridge
    name: ftnet
    external: true

volumes:
  mongo_data:
    driver: local

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 9999
