# Use root/example as user/password credentials
version: '3.5'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9999
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.10:27017:27017"
    networks:
      - ftnet

  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi
    container_name: app
    volumes:
      - ./server:/app
    ports:
      - "127.0.1.20:8000:80"
    entrypoint: "/app/docker_start.sh"
    # command: [ "bash", "-c", "curl -v -XPUT http://localhost:80/migrate"]
    networks:
      - ftnet
    healthcheck:
      test: ["CMD", "pytest", "tests"]

networks:
  ftnet:
    driver: bridge
    name: ftnet
    # external: true

volumes:
  mongo_data:
    driver: local
